name: Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

env:
  SOLUTION_FILE_PATH: MixSets/MixSets.vcxproj
  BUILD_CONFIGURATION: GTASA Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout plugin-sdk
      uses: actions/checkout@v4
      with:
        repository: DK22Pac/plugin-sdk
        path: plugin-sdk

    - name: Setup plugin-sdk environment
      run: |
        echo "PLUGIN_SDK_DIR=${{ github.workspace }}\plugin-sdk" >> $env:GITHUB_ENV

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Update Premake5
      working-directory: ${{ github.workspace }}\plugin-sdk\tools\premake
      run: |
        Invoke-WebRequest -Uri "https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip" -OutFile "premake5.zip"
        Expand-Archive -Path "premake5.zip" -DestinationPath "." -Force
        Remove-Item "premake5.zip"

    - name: Generate plugin-sdk project files
      working-directory: ${{ github.workspace }}\plugin-sdk\tools\premake
      run: .\premake5.exe vs2022

    - name: Build plugin-sdk
      working-directory: ${{ github.workspace }}\plugin-sdk
      run: msbuild /m /p:Configuration=Release plugin.sln

    - name: Verify plugin-sdk library
      run: |
        if (Test-Path "${{ github.workspace }}\plugin-sdk\output\lib\Plugin.lib") {
            echo "Plugin.lib found."
        } else {
            echo "Plugin.lib NOT found in ${{ github.workspace }}\plugin-sdk\output\lib\"
            dir "${{ github.workspace }}\plugin-sdk\output" -Recurse
            exit 1
        }

    - name: Build MixSets
      working-directory: ${{ github.workspace }}
      run: msbuild /m /p:Configuration="${{ env.BUILD_CONFIGURATION }}" ${{ env.SOLUTION_FILE_PATH }} /p:Platform=Win32 /p:OutDir="${{ github.workspace }}\bin\\" /p:PlatformToolset=v143 /p:LanguageStandard=stdcpplatest /flp:logfile=msbuild.log;verbosity=diagnostic

    - name: Print Build Log
      if: failure()
      run: type msbuild.log

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MixSets
        path: |
            bin/**/*.asi
            bin/**/*.pdb
