name: Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

env:
  SOLUTION_FILE_PATH: MixSets.sln
  BUILD_CONFIGURATION: GTASA Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout plugin-sdk
      uses: actions/checkout@v4
      with:
        repository: DK22Pac/plugin-sdk
        path: plugin-sdk

    - name: Setup plugin-sdk environment
      run: |
        echo "PLUGIN_SDK_DIR=${{ github.workspace }}\plugin-sdk" >> $env:GITHUB_ENV

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Generate plugin-sdk project files
      working-directory: ${{ github.workspace }}\plugin-sdk\tools\premake
      run: .\premake5.exe vs2022

    - name: Build plugin-sdk
      working-directory: ${{ github.workspace }}\plugin-sdk
      run: msbuild /m /p:Configuration=Release plugin.sln

    - name: Build MixSets
      working-directory: ${{ github.workspace }}
      run: msbuild /m /p:Configuration="${{ env.BUILD_CONFIGURATION }}" ${{ env.SOLUTION_FILE_PATH }} /p:Platform=x86 /p:OutDir="${{ github.workspace }}\bin\\" /p:PlatformToolset=v143

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MixSets
        path: |
            bin/**/*.asi
            bin/**/*.pdb
